// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:w
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK2unpOUTUcNZnyxbwrY-6M4ew2hhDm54',
    appId: '1:188807963971:android:a76dede7f0a237a93a3bf6',
    messagingSenderId: '188807963971',
    projectId: 'shop-i-de05b',
    databaseURL: 'https://shop-i-de05b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-i-de05b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsEmJ3yIYeAvMxDT_252Z9vaqjsK84KHQ',
    appId: '1:188807963971:ios:fbbfa2f2552794c43a3bf6',
    messagingSenderId: '188807963971',
    projectId: 'shop-i-de05b',
    databaseURL: 'https://shop-i-de05b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-i-de05b.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Omt3fpW7oyBmM0xoNhzbjMFfcS4GSug',
    appId: '1:188807963971:web:5affcc100b6849ba3a3bf6',
    messagingSenderId: '188807963971',
    projectId: 'shop-i-de05b',
    authDomain: 'shop-i-de05b.firebaseapp.com',
    databaseURL: 'https://shop-i-de05b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-i-de05b.appspot.com',
    measurementId: 'G-Z07FGE948V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Omt3fpW7oyBmM0xoNhzbjMFfcS4GSug',
    appId: '1:188807963971:web:5affcc100b6849ba3a3bf6',
    messagingSenderId: '188807963971',
    projectId: 'shop-i-de05b',
    authDomain: 'shop-i-de05b.firebaseapp.com',
    databaseURL: 'https://shop-i-de05b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-i-de05b.appspot.com',
    measurementId: 'G-Z07FGE948V',
  );

}